# Generated by Django 6.0.5 on 2026-05-12 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('topic', models.TextField()),
                ('niche', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('content_style', models.CharField(max_length=100)),
                ('folder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('hook', models.TextField()),
                ('main_script', models.TextField()),
                ('cta', models.TextField()),
                ('hashtags', models.TextField()),
                ('viral_score', models.IntegerField(default=0)),
                ('ai_model', models.CharField(default='gemini', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_order', models.IntegerField()),
                ('timestamp', models.CharField(max_length=50)),
                ('visual', models.TextField()),
                ('narrative', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('script_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='api.scriptversion')),
            ],
            options={
                'ordering': ['scene_order'],
            },
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('script_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='api.scriptversion')),
            ],
        ),
    ]
