# Generated by Django 6.0.5 on 2026-05-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collection_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
